### PR TITLE
Update printer.py

### PR DESCRIPTION
**Pull request by weic6**
add a if block to assure correct start up

### CODE REVIEW

**Comment by 123aaaaaaaaaaaaaaaaaaaaa** [comment]
this if is redundant.

**Comment by weic6** [comment]
no, activation of printer need to print message to inform user

**Comment by 123aaaaaaaaaaaaaaaaaaaaa** [comment]
> add a if block to assure correct start up
this if is redundant.

**Comment by 123aaaaaaaaaaaaaaaaaaaaa** [comment]
> this if is redundant.

this if is redundant.

**Comment by 123aaaaaaaaaaaaaaaaaaaaa** [comment]
yes, correct. request accepted

**Comment by weic6** [comment]
yes, correct. request accepted

**Comment by 123aaaaaaaaaaaaaaaaaaaaa** [comment]
Hi, i found other problems, ...

**Comment by weic6** [comment]
> Hi, i found other problems, ...

**Comment by weic6** [comment]
good point, will merge

**Pull request merged**
